name: just-echo
on:
    schedule:
      - cron: '1 1 1 1 *'

jobs:
    just-echo:
        runs-on: ubuntu-latest
        steps:
          - name: Echo
            run: echo "Hello world!" && false
          - name: Echo final
            run: echo "World finalized"
            if: always() && ${{ !inputs.skip }}
